#ifndef NS3_CONFIG_STORE_CONFIG_H
#define NS3_CONFIG_STORE_CONFIG_H

#cmakedefine PYTHONDIR @PYTHONDIR_STRING@
#cmakedefine PYTHONARCHDIR @PYTHONARCHDIR_STRING@
#cmakedefine HAVE_PYEMBED
#cmakedefine HAVE_PYEXT
#cmakedefine HAVE_PYTHON_H

#endif //NS3_CONFIG_STORE_CONFIG_H
