title: ns-3 with CMake
description: >- 
  Eliminating the waffle carbs.
baseurl: "/NS3" 
url: "https://gabrielcarvfer.github.io/" 
twitter_username: gabrielcarvfer
github_username:  gabrielcarvfer

header_pages:
  - index.md
  - installation.md
  - oran.md
  - 5g-range.md
  - colab-5g.md
  - collab.md
  - dynamicBeacon.md

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

