name: Mac_OS_X

on: [push]
  #schedule:
#  - cron:  '0 5 * * *'  #daily build at 5AM
jobs:
  Mac_OS_X:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: |
          brew install ninja cmake gcc@9 #qt5
      - name: Configure CMake
        run: |
          export PATH=/usr/local/bin:$PATH #:/usr/local/opt/qt/bin
          export CXX=g++-9
          export CC=gcc-9
          mkdir cmake-cache
          cd cmake-cache
          cmake -DCMAKE_BUILD_TYPE=minsizerel -DNS3_EXAMPLES=ON -DNS3_TESTS=ON -G"Ninja" ..
      - name: Build ns-3
        run: |
          export PATH="$PATH" #:/usr/local/opt/qt/bin
          cd cmake-cache
          ninja
      -  name: Run tests
         run: |
           python3 ./utils/test-runner-script.py
      -  name: Run examples
         run : |
           cd cmake-cache
           ctest -j 4 --timeout 800
    #  - name: Clean release with debug artifacts
    #    run: |
    #      rm -Rf ../build
    #      rm -Rf ./*
    #      rm -Rf ../3rd-party/vcpkg
    #      rm ../utils/failed-tests.json

