name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get -y install apt-utils
        sudo apt-get -y install git gcc g++ cmake python make ninja-build
        sudo apt-get -y install qt4-default 
        sudo apt-get -y install gdb valgrind
        sudo apt-get -y install tcpdump 
        sudo apt-get -y install curl unzip tar  
        sudo apt-get -y install ccache 
    - name: Configure CMake
      run: |
        mkdir cmake-cache 
        cd cmake-cache
        cmake -DCMAKE_BUILD_TYPE=RELEASE -G"Ninja" .. 
    - name: Build ns-3    
      run: |
        cd cmake-cache
        ninja
    -  name: Run tests
       run: |
         python3 ./utils/test-runner-script.py    
     
