name: Windows_Visual_Studio

on: [push]
  #schedule:
#  - cron:  '0 5 * * *'  #daily build at 5AM
jobs:
  Windows_Visual_Studio:   
  
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
          python-version: 3.7
    - name: Configure CMake
      run: |
        %comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        mkdir cmake-cache
        cd cmake-cache
        cmake -DCMAKE_BUILD_TYPE=minsizerel -DNS3_EXAMPLES=ON -DNS3_TESTS=ON -G"Visual Studio 16 2019" -A x64 -T ClangCL ..
      shell: cmd
    - name: Build ns-3
      run: |
        %comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        cd cmake-cache
        cmake --build . --parallel 4
      shell: cmd
    - name: Run tests
      run: |
        cd build
        python ..\utils\test-runner-script.py
      shell: cmd
    - name: Run examples
      run : |
        %comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        cd cmake-cache
        ctest -j 4 --timeout 800
      shell: cmd